<template><div><h1 id="ubuntu20-04搭建prometheus" tabindex="-1"><a class="header-anchor" href="#ubuntu20-04搭建prometheus"><span>Ubuntu20.04搭建Prometheus</span></a></h1>
<blockquote>
<p>https://blog.csdn.net/zfgylbcc/article/details/137177631</p>
</blockquote>
<p>promethus的启动、停止：</p>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" data-title="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span>/etc/init.d/prometheus start/stop/restart</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>启动报错，找不到deamond</p>
<div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" data-title="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sudo</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> apt-get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> update</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sudo</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> apt-get</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> daemon</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-shell line-numbers-mode" data-highlighter="shiki" data-ext="shell" data-title="shell" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 注意后面的#号</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sudo</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -u</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> node_exporter_user</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./node_exporter</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --web.listen-address=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"183.233.197.205:9100"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --log.level=info</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x26;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sudo</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -u</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> node_exporter</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./node_exporter</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --web.listen-address=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"0.0.0.0:9100"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --log.level=debug</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


